### ISSUE TITLE
Optimize trips API Swagger UI base host URL

### ISSUE THREAD

**Issue by dtzar** [Azure-Samples/openhack-devops-team#135]
The swagger UI for trips API requires a base URL and it is [set by default](https://github.com/Azure-Samples/openhack-devops-team/blob/4ac8aee55b2a39fbb1a6e1c3dd402b2adaa387a4/apis/trips/helm/values.yaml#L14) to `http://localhost`.  It would be a better experience if [this value is set ](https://github.com/Azure-Samples/openhack-devops-team/blob/4ac8aee55b2a39fbb1a6e1c3dd402b2adaa387a4/apis/trips/helm/templates/deployment.yaml#L66) to `http://` + [ingress.rules.endpoint.host](https://github.com/Azure-Samples/openhack-devops-team/blob/4ac8aee55b2a39fbb1a6e1c3dd402b2adaa387a4/apis/trips/helm/values.yaml#L23) instead of the separate value.

**Comment by DariuszPorowski** [comment]
expired
