### ISSUE TITLE
Can we use Azure VM Agents plugin in Jenkins without creating admin username and password

### ISSUE THREAD

**Issue by hakimkartik** [Azure-Samples/openhack-devops-team#171]
I was trying to use the azure-vm-agents plugin in our jenkins platform so that whenever the load increases and all the executors are occupied, a new VM agent can be launched on the fly.
But while configuring the plugin in the last section where we describe the template, we were struck at step `Specify Admin Credentials` (step 11 in https://wiki.jenkins.io/display/JENKINS/Azure+VM+Agents+plugin) as in our infrastructure we do not use username and password to login to our VM agents, we use RSA public / private keys.

Is there some way we can skip this step while configuring the template or add the private key itself ?

**Comment by polatengin** [comment]
With the upcoming new content, we're not going to use a dedicated VM for Jenkins.

I think we can close this issue.

/cc: @BSamodien
