### ISSUE TITLE
Add support for log export to prometheus/Azure Monitor endpoints

### ISSUE THREAD

**Issue by polatengin** [Azure-Samples/openhack-devops-team#206]

**Comment by polatengin** [comment]
Attendees can create an Azure Dashboard ([Create and share dashboards in the Azure portal](https://docs.microsoft.com/en-us/azure/azure-portal/azure-portal-dashboards) and [Programmatically create Azure Dashboards](https://docs.microsoft.com/en-us/azure/azure-portal/azure-portal-dashboards-create-programmatically))

Azure Monitor service let's you create charts and grids based on metrics/logs from your resources ([Metrics in Azure Monitor](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/data-platform-metrics) and [Logs in Azure Monitor](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/data-platform-logs))

Attendee can create a chart for Http Request Queue for example and pin it to the Dashboard. so, attendees can create as much chart/grid as they want to have an overview for resources.

If they want to have Grafana dashboard, there are 2 main ways to do that;
* in the New Resource blade, search for Grafana and create 1 in the Azure Portal, so you can manage Grafana
* you can create a free account on [Create your free Grafana Cloud Account](https://grafana.com/signup/starter/connect-account)

After having a Grafana account, attendee should install Azure Monitor plugin ([Azure Monitor Plugin from Grafana Labs](https://grafana.com/grafana/plugins/grafana-azure-monitor-datasource)) and configure it (https://grafana.com/docs/grafana/latest/features/datasources/azuremonitor/, https://www.ciraltos.com/connect-grafana-to-azure-log-analytics/)

Azure Monitor always collect logs and metrics from resources on Azure, Grafana can tap into that stream and let attendee create a dashboard on Grafana.

**Comment by DariuszPorowski** [comment]
Hey @polatengin
Can you handle it?

**Comment by polatengin** [comment]
yeah, sure. let's discuss it on Monday

**Comment by DariuszPorowski** [comment]
issue moved to https://github.com/Microsoft-OpenHack/devops/issues/348
