### ISSUE TITLE
Suggest changing repo type to 'template'

### ISSUE THREAD

**Issue by larryclaman** [Azure-Samples/openhack-devops-team#292]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
During openhack, attendees are told:
```
Create your own code repository either by forking the provided repo on GitHub or import into GitHub.

Note: Downloading and extracting an archived version of the repo locally (instead of forking) if you are following the GitHub route may be beneficial as it will narrow down the choices that your team will need to make when you are in the process of creating Pull Requests against your default branch.
```
I suggest that this repo be changed to a Template repository , whichlet users generate new repositories with the same directory structure and files but without having to fork the repo.  see https://docs.github.com/articles/creating-a-repository-from-a-template/

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by DariuszPorowski** [comment]
it makes sense! enabled :)
