### ISSUE TITLE
POI Dockerfile needs update to point to new dotnetcore base images

### ISSUE THREAD

**Issue by larryclaman** [Azure-Samples/openhack-devops-team#293]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
POI dockerfile no longer works due to renaming of dotnetcore base images.  see https://devblogs.microsoft.com/dotnet/net-core-2-1-container-images-will-be-deleted-from-docker-hub/

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Sam-Rowe** [comment]
I bumped into this today as well. 

Using the mcr.microsoft.com images still works so should be simple change to https://github.com/Azure-Samples/openhack-devops-team/blob/master/apis/poi/web/Dockerfile

Change out line 1 for 
`FROM mcr.microsoft.com/dotnet/sdk:2.1 AS build-env`

and line 15 for
`FROM mcr.microsoft.com/dotnet/core/runtime:2.1`
